### ISSUE TITLE
Using issues for discussion?

### ISSUE THREAD

**Issue by ricklupton** [IndEcol/OpenScience#1]
As an alternative to [storing discussions in the 'meta' wiki as Niko suggested](https://github.com/IndEcol/OpenScience/wiki/Wiki-structure), how about using GitHub issues?

They more naturally have the structure of a conversation, can be closed and archived, organised with tags, and you can @nheeren @stefanpauliuk @rjmyers mention people to get their attention specifically.

But I haven't used either method in practice, so just a suggestion.

**Comment by rjmyers** [comment]
Sounds good to me @ricklupton .

**Comment by konstantinstadler** [comment]
Hi,

I am very much in favour of this.
We (digilab ntnu) strive to have all repo related discussion in issues 
and it works great (following 
http://www.yegor256.com/2016/08/23/communication-maturity.html)

**Comment by nheeren** [comment]
Of course! Makes much more sense
