### ISSUE TITLE
licence

### ISSUE THREAD

**Issue by konstantinstadler** [IndEcol/OpenScience#2]
Any reason for GNU licence?
Can we have cc-by (https://creativecommons.org/licenses/by/4.0/)

**Comment by stefanpauliuk** [comment]
I chose GNU from the suggested licenses because of its permissiveness and the fact that here we mostly exchange ideas, not software. But CC-BY is also very fine with me ;)

**Comment by konstantinstadler** [comment]
I thought, GNU is mainly designed for software and CC-BY is the appropriate one for open data and text.

Anyone else has better insight?

**Comment by nheeren** [comment]
Does that mean we change the license? FYI: [Wikipedia uses mostly CC BY-SA v3.0](https://en.wikipedia.org/wiki/Wikipedia:Copyrights).

**Comment by konstantinstadler** [comment]
I was thinking about CC-BYv4.0 
https://creativecommons.org/licenses/by/4.0/

**Comment by nheeren** [comment]
Agree. Let's go?

**Comment by konstantinstadler** [comment]
ok, done
